using System;
using System.Linq;
using System.Collections.Generic;
using LittleWeeps.Core;
using UnityEngine;
using UnityEngine.UI;
namespace LittleWeeps.Client {
 public sealed partial class GameScreen {
  private RectTransform treasureHud,treasureBelt,treasureOpening,treasureEnding,treasureChest,treasureChimes,treasureTeacher,treasureMap;
  private readonly List<RectTransform> treasureMapMarks=new List<RectTransform>();
  private RawImage treasureTeacherPicture;private TeacherWalkView treasureTeacherWalk;private Vector2 treasureTeacherPoint;private float treasureDemoStartAt;
  private Text treasureHint,treasureProgress;private TreasureShape treasureClue;private bool treasureSending,treasureMystery;
  private string treasureApproach="",treasureOperation="";private int treasureSpoken=-1,treasureRound=-1,treasureFrame=-1,treasureDemoNote=-1;
  private double treasureDemoAt=-11,treasureClockRendered;private readonly NpcPresentationClock treasurePresentationClock=new NpcPresentationClock();private readonly NpcLocomotion treasureTeacherLocomotion=new NpcLocomotion();private AudioSource treasureTone;
  private readonly List<TreasureShape> treasureCovers=new List<TreasureShape>(),treasureFinds=new List<TreasureShape>(),treasureMounds=new List<TreasureShape>(),treasurePieces=new List<TreasureShape>(),treasureActionIcons=new List<TreasureShape>();
  private readonly List<Button> treasureActions=new List<Button>();private readonly List<Text> treasureActionLabels=new List<Text>();private readonly List<AudioClip> treasureAudio=new List<AudioClip>();private AudioClip[] treasureNotes;
  private readonly List<(RectTransform root,GameCharacterVisual visual)> treasureFriends=new List<(RectTransform,GameCharacterVisual)>();private readonly List<Vector2> treasureNpcPoints=new List<Vector2>();private readonly List<NpcLocomotion> treasureMotion=new List<NpcLocomotion>();
  public TreasureState TreasureGame=>HasWorld?(Shared?shared.View.treasure:World.ReadTreasure()):null;
  public string TreasureFeedback=>homeFeedback!=null && Time.unscaledTime<homeFeedbackUntil?homeFeedback.text:"";
  public int TreasureDemoNote=>treasureDemoNote;public bool TreasureTonePlaying=>treasureTone!=null && treasureTone.isPlaying;
  public string[] TreasureNpcArt=>treasureFriends.Select(n=>n.visual.CharacterId).ToArray();public Vector2[] TreasureNpcPoints=>treasureNpcPoints.ToArray();public string[] TreasureNpcPoses=>treasureFriends.Select(n=>n.visual.Frame.Pose.ToString()).ToArray();public float[] TreasureNpcSpeeds=>treasureFriends.Select(n=>n.visual.Frame.Speed).ToArray();public int[] TreasureNpcFrames=>treasureFriends.Select(n=>n.visual.ActiveView==null?-1:n.visual.ActiveView.FrameIndex).ToArray();public float[] TreasureNpcPhases=>treasureFriends.Select(n=>n.visual.ActiveView==null?0:n.visual.ActiveView.WalkPhase).ToArray();public string TreasureApproach=>treasureApproach;public bool TreasureMystery=>treasureMystery;
  private bool TreasureOwn=>TreasureGame?.members.Any(m=>m.actor==Actor && m.attending)==true;
  private TreasureShape TreasurePicture(Transform parent,string name,Vector2 at,Vector2 size,string kind){var shape=Rect(parent,name,at,size).gameObject.AddComponent<TreasureShape>();shape.kind=kind;shape.raycastTarget=false;return shape;}
  private void ChooseTreasure(){CloseMiniGames();CloseNavigation();Narration.Stop();SendTreasure("start");}
  private void SendTreasure(string op,string target=""){
   if(!Ready || TravelPending || treasureSending && op!="leave")return;treasureSending=true;treasureApproach="";destination=null;CancelPointers();manualCamera=false;shared?.Walk(WalkMode.Stop);
   void Done(SoloResult r){treasureSending=false;if(!r.Accepted){homeFeedback.text=r.Outcome=="match-map-pictures"?"Match the chest pictures to map pieces 1, 2 and 3.":"Follow our current clue. Tap Show me for a hand.";homeFeedbackUntil=Time.unscaledTime+4;}else if(op=="lift" || op=="dig"){if(TreasureGame.lastFind>0)Narration.Speak("treasure-surprise");}else if(op=="note"){if(TreasureGame.tuneStep==0)Narration.Speak("treasure-retry");else if(int.TryParse(target,out var n) && treasureNotes[n]!=null)treasureTone.PlayOneShot(treasureNotes[n]);}Render();}
   if(Shared){if(!SubmitShared(SoloAction.Treasure,"",target,op,0,0,Done))treasureSending=false;}else Done(Command(SoloAction.Treasure,target:target,value:op));
  }
  private void RequestTreasure(string target,string op){if(!Ready || MenuOpen || !TreasureOwn)return;CancelPointers();treasureApproach=target;treasureOperation=op;manualCamera=false;var at=op=="wheel"?TreasureHunt.Dig(TreasureGame.site):TreasureHunt.Point(TreasureGame,target);destination=new Vector2(at.X,at.Y);}
  private void CheckTreasureInput(){
   if(treasureApproach=="")return;if(CurrentArea!=TreasureHunt.Zone || !TreasureOwn || MenuOpen || applicationPaused || stickDirection.sqrMagnitude>.1f){treasureApproach="";destination=null;return;}
   if(treasureSending || ActionPending)return;var at=treasureOperation=="wheel"?TreasureHunt.Dig(TreasureGame.site):TreasureHunt.Point(TreasureGame,treasureApproach);var p=ReadPlayer(Actor);if(Math.Abs(p.x-at.X)>15 || Math.Abs(p.y-at.Y)>25)return;
   if(treasureOperation=="visit"){treasureApproach="";destination=null;shared?.Walk(WalkMode.Stop);return;}SendTreasure(treasureOperation,treasureApproach);
  }
  private void TreasureHelp(){var g=TreasureGame;if(g==null || g.phase<2)return;treasureMystery=false;RequestTreasure(TreasureHunt.Next(g),"visit");SpeakTreasure();}
  private void SpeakTreasure(){var g=TreasureGame;if(g==null)return;Narration.Speak("treasure-"+(g.phase==5?"site-"+g.site:treasureMystery && g.phase>=2 && g.phase<=4?"mystery-"+g.phase:"step-"+g.phase));}
  private void TreasureAction(int i){var g=TreasureGame;if(g==null)return;
   if(g.phase==2 || g.phase==3){var index=(g.phase==2?0:3)+i;var correct=index==(g.phase==2?g.shell:3+g.pot);RequestTreasure("cover-"+index,g.lifted[index] && correct?"take":"lift");}
   else if(g.phase==4)RequestTreasure(i.ToString(),"note");else if(g.phase==5)RequestTreasure("dig-"+i,"dig");else if(g.phase==6)RequestTreasure(i.ToString(),"wheel");
  }
  private void BuildTreasure(){
   if(SceneSchema<TreasureHunt.Schema)return;
   for(var i=0;i<6;i++){var index=i;var cover=TreasurePicture(Board,"Treasure hiding place "+i,Vector2.zero,new Vector2(155,175),i<3?"shell":"pot");treasureCovers.Add(cover);HomeHit(cover.transform,"Search treasure hiding place "+i,new Vector2(0,35),new Vector2(160,150),()=>{var g=TreasureGame;if(g.phase==2 && index<3 || g.phase==3 && index>=3){var correct=index==(g.phase==2?g.shell:3+g.pot);RequestTreasure("cover-"+index,g.lifted[index] && correct?"take":"lift");}},false);var find=TreasurePicture(Board,"Hidden treasure discovery "+i,Vector2.zero,new Vector2(110,110),"map");treasureFinds.Add(find);HomeHit(find.transform,"Take map piece "+i,Vector2.zero,new Vector2(125,100),()=>RequestTreasure("cover-"+index,"take"),false);}
   treasureChimes=TreasurePicture(Board,"Windchime music tree",Vector2.zero,new Vector2(280,180),"chimes").rectTransform;
   for(var i=0;i<3;i++){var index=i;var mound=TreasurePicture(Board,"Treasure sand mound "+i,Vector2.zero,new Vector2(160,70),"dig");treasureMounds.Add(mound);HomeHit(mound.transform,"Dig treasure mound "+i,Vector2.zero,new Vector2(170,90),()=>RequestTreasure("dig-"+index,"dig"),false);}
   treasureChest=TreasurePicture(Board,"Calypso surprise chest",Vector2.zero,new Vector2(220,190),"chest").rectTransform;HomeHit(treasureChest,"Open treasure chest",new Vector2(0,30),new Vector2(240,160),()=>RequestTreasure("chest","open"),false);
   for(var i=0;i<3;i++){var index=i;var root=Rect(Board,"Treasure friend "+i,Vector2.zero,new Vector2(160,220));treasureFriends.Add((root,root.gameObject.AddComponent<GameCharacterVisual>()));treasureNpcPoints.Add(Vector2.zero);treasureMotion.Add(new NpcLocomotion());var prop=TreasurePicture(root,"Friend's treasure tool",new Vector2(45,93),new Vector2(80,80),i==1?"pot":i==2?"symbol":"map");prop.rectTransform.localScale=Vector3.one*.48f;HomeHit(root,"Talk to treasure friend "+i,new Vector2(0,90),new Vector2(170,210),()=>{if(index==2 && TreasureGame.phase==4)SendTreasure("listen");else SpeakTreasure();},false);}
   treasureTeacher=Rect(Board,"Treasure Calypso",Vector2.zero,new Vector2(170,250));treasureTeacherPicture=Rect(treasureTeacher,"Calypso treasure drawing",new Vector2(0,130),new Vector2(220,294)).gameObject.AddComponent<RawImage>();treasureTeacherPicture.texture=calypsoTexture;treasureTeacherPicture.raycastTarget=false;treasureTeacherWalk=treasureTeacher.gameObject.AddComponent<TeacherWalkView>();treasureTeacherWalk.Configure(treasureTeacherPicture,calypsoTexture);HomeHit(treasureTeacher,"Talk to treasure Calypso",new Vector2(0,110),new Vector2(190,240),SpeakTreasure,false);
   treasureHud=Panel(safe,"Treasure clue",Vector2.zero,new Vector2(1000,112),new Color(1,.97f,.86f,.97f),false).rectTransform;treasureHud.anchorMin=treasureHud.anchorMax=new Vector2(.5f,1);treasureHud.anchoredPosition=new Vector2(0,-170);
   treasureClue=TreasurePicture(treasureHud,"Picture clue",new Vector2(-415,0),new Vector2(100,95),"shell");treasureClue.rectTransform.localScale=Vector3.one*.8f;
   treasureHint=Label(treasureHud,"",25,new Vector2(-25,5),new Vector2(665,100));Button(treasureHud,"Return",new Vector2(410,0),new Vector2(130,80),()=>{Narration.Stop();SendTreasure("leave");},Color.white).fontSize=25;
   treasureBelt=Panel(safe,"Treasure picture tools",Vector2.zero,new Vector2(1000,173),new Color(1,.97f,.86f,.98f),false).rectTransform;treasureBelt.anchorMin=treasureBelt.anchorMax=new Vector2(.5f,0);treasureBelt.anchoredPosition=new Vector2(0,95);
   for(var i=0;i<3;i++){var piece=TreasurePicture(treasureBelt,"Shared map fragment "+(i+1),new Vector2(-380+i*90,39),new Vector2(80,70),"map");piece.rectTransform.localScale=Vector3.one*.65f;Label(piece.transform,(i+1).ToString(),24,new Vector2(-23,21),new Vector2(28,30));treasurePieces.Add(piece);}
   HomeHit(treasureBelt,"Open our treasure map",new Vector2(-290,40),new Vector2(270,85),()=>treasureMap.gameObject.SetActive(true),false);
   treasureProgress=Label(treasureBelt,"",19,new Vector2(-290,75),new Vector2(300,28));
   Button(treasureBelt,"Listen",new Vector2(-65,43),new Vector2(140,54),()=>{SpeakTreasure();if(TreasureGame.phase==4)SendTreasure("listen");},Color.white).fontSize=22;
   Button(treasureBelt,"Picture / riddle",new Vector2(135,43),new Vector2(240,54),()=>{treasureMystery=!treasureMystery;SpeakTreasure();},new Color(.87f,.83f,.98f)).fontSize=23;
   Button(treasureBelt,"Show me",new Vector2(360,43),new Vector2(175,54),TreasureHelp,new Color(.82f,.91f,.62f)).fontSize=23;
   for(var i=0;i<3;i++){var index=i;var label=Button(treasureBelt,"",new Vector2(-300+i*210,-36),new Vector2(195,83),()=>TreasureAction(index),Color.white);label.fontSize=21;label.rectTransform.anchoredPosition=new Vector2(0,-23);label.rectTransform.sizeDelta=new Vector2(185,32);treasureActionLabels.Add(label);label.transform.parent.name="Treasure action "+(i+1);treasureActions.Add(label.transform.parent.GetComponent<Button>());var icon=TreasurePicture(label.transform.parent,"Hunt action picture",new Vector2(0,17),new Vector2(85,60),"shell");icon.rectTransform.localScale=Vector3.one*.48f;treasureActionIcons.Add(icon);}
   var extra=Button(treasureBelt,"",new Vector2(355,-36),new Vector2(190,83),()=>{var g=TreasureGame;if(g.phase==6)RequestTreasure("chest","open");else if(g.phase==7)SendTreasure("replay");else if(g.phase==4){Narration.Stop();SendTreasure("listen");}},new Color(.82f,.91f,.62f));extra.fontSize=23;treasureActionLabels.Add(extra);extra.transform.parent.name="Treasure main action";treasureActions.Add(extra.transform.parent.GetComponent<Button>());
   treasureOpening=Panel(safe,"The Windblown Map opening",Vector2.zero,new Vector2(870,460),new Color(1,.97f,.87f),true).rectTransform;
   Label(treasureOpening,"The Windblown Map",42,new Vector2(0,170),new Vector2(800,70));Label(treasureOpening,@"Calypso hid a surprise on our pretend island.
But a gust scattered the treasure map!

Search with our friends, copy the windchime song,
and put the map back together.
What will we find inside the chest?",29,new Vector2(0,10),new Vector2(800,245));
   Button(treasureOpening,"Listen to our story",new Vector2(-195,-170),new Vector2(340,70),SpeakTreasure,Color.white).fontSize=25;Button(treasureOpening,"Start exploring!",new Vector2(195,-170),new Vector2(340,70),()=>SendTreasure("begin"),new Color(.82f,.91f,.62f)).fontSize=27;
   treasureEnding=Rect(Board,"Our treasure toys",Vector2.zero,new Vector2(270,90));for(var i=0;i<3;i++){var toy=TreasurePicture(treasureEnding,"Treasure keepsake "+i,new Vector2(-95+i*95,0),new Vector2(90,90),new[]{"compass","symbol","boat"}[i]);toy.symbol=2;}
   treasureMap=Panel(safe,"Our island treasure map",Vector2.zero,new Vector2(850,430),new Color(1,.94f,.76f),true).rectTransform;NavButton(treasureMap.GetComponent<Image>(),()=>{});
   Label(treasureMap,"Our island map",36,new Vector2(0,163),new Vector2(780,55));
   for(var i=0;i<3;i++){var x=-270+i*270;var landmark=TreasurePicture(treasureMap,"Map landmark "+i,new Vector2(x,35),new Vector2(150,130),new[]{"palm","flowers","lookout"}[i]);landmark.rectTransform.localScale=Vector3.one*1.1f;Label(treasureMap,TreasureHunt.Landmark(i),25,new Vector2(x,-62),new Vector2(260,48));var mark=Label(treasureMap,"X",44,new Vector2(x,105),new Vector2(55,60));mark.color=new Color(.88f,.3f,.25f);treasureMapMarks.Add(mark.rectTransform);}
   for(var i=0;i<9;i++)Plain(treasureMap,"Map trail",new Vector2(-205+i*52,-14),new Vector2(22,5),new Color(.69f,.49f,.28f));
   Label(treasureMap,"Find the three pieces. Their pictures open the chest!",23,new Vector2(0,-116),new Vector2(780,48));Button(treasureMap,"Back to exploring",new Vector2(-205,-175),new Vector2(340,65),()=>treasureMap.gameObject.SetActive(false),Color.white).fontSize=25;Button(treasureMap,"Follow our clue",new Vector2(200,-175),new Vector2(340,65),()=>{treasureMap.gameObject.SetActive(false);TreasureHelp();},new Color(.82f,.91f,.62f)).fontSize=25;treasureMap.gameObject.SetActive(false);
   treasureTone=treasureBelt.gameObject.AddComponent<AudioSource>();treasureTone.playOnAwake=false;treasureTone.spatialBlend=0;treasureTone.volume=.55f;treasureNotes=Enumerable.Range(0,3).Select(i=>WorldResources.Load<AudioClip>("Worlds/Daycare/TreasureHunt/note-"+i)).ToArray();treasureAudio.AddRange(treasureNotes.Where(c=>c!=null));
   foreach(var id in new[]{"step-1","step-2","step-3","step-4","site-0","site-1","site-2","step-6","step-7","mystery-2","mystery-3","mystery-4","surprise","retry"}){var clip=WorldResources.Load<AudioClip>("Worlds/Daycare/TreasureHunt/"+id);if(clip!=null){treasureAudio.Add(clip);Narration.AddClip("treasure-"+id,clip);}}
   TickTreasure();
  }
  private void TickTreasure(){
   if(treasureHud==null || treasureFrame==Time.frameCount)return;treasureFrame=Time.frameCount;var g=TreasureGame;var visible=CurrentArea==TreasureHunt.Zone && g!=null;
   if(g!=null)treasureClockRendered=treasurePresentationClock.Step(g.clock,"treasure/"+g.round,
    Shared && shared.Connected,Time.unscaledTimeAsDouble,Mathf.Min(Time.unscaledDeltaTime,.1f));

   var own=visible && TreasureOwn && !MenuOpen;var dt=Mathf.Min(Time.unscaledDeltaTime,.1f);
   treasureHud.gameObject.SetActive(own && g.phase!=1);treasureBelt.gameObject.SetActive(own && g.phase!=1);treasureOpening.gameObject.SetActive(own && g.phase==1);var scale=Mathf.Min(1,safe.rect.width/1060);treasureHud.localScale=treasureBelt.localScale=Vector3.one*scale;treasureOpening.localScale=Vector3.one*Mathf.Min(safe.rect.width/930,safe.rect.height/550);if(treasureOpening.gameObject.activeSelf)treasureOpening.SetAsLastSibling();
   for(var i=0;i<6;i++){var root=treasureCovers[i].rectTransform;root.gameObject.SetActive(visible);treasureFinds[i].gameObject.SetActive(false);if(!visible)continue;var at=TreasureHunt.Cover(i);var correct=i==(i<3?g.shell:3+g.pot);var lifted=g.lifted[i];root.anchoredPosition=ToBoard(at.X,at.Y)+new Vector2(lifted?65:0,lifted?66:20)*sceneScale;root.localScale=Vector3.one*sceneScale;treasureCovers[i].special=correct;treasureCovers[i].count=correct?3:i%3+1==3?2:1;treasureCovers[i].SetVerticesDirty();var find=treasureFinds[i];find.gameObject.SetActive(lifted && (!correct || (i<3?g.phase==2:g.phase==3)));find.kind=correct?"map":i<3?"crab":"boot";find.symbol=g.tune[i<3?0:1];find.rectTransform.anchoredPosition=ToBoard(at.X,at.Y)+new Vector2(0,5)*sceneScale;find.rectTransform.localScale=Vector3.one*sceneScale;find.SetVerticesDirty();}
   treasureChimes.gameObject.SetActive(visible);if(visible){treasureChimes.anchoredPosition=ToBoard(3900,360);treasureChimes.localScale=Vector3.one*sceneScale;}
   for(var i=0;i<3;i++){var root=treasureMounds[i].rectTransform;root.gameObject.SetActive(visible && !(g.phase>=6 && i==g.site));if(visible){var at=TreasureHunt.Dig(i);root.anchoredPosition=ToBoard(at.X,at.Y);root.localScale=Vector3.one*sceneScale;}}
   treasureChest.gameObject.SetActive(visible && g.phase>=6);treasureEnding.gameObject.SetActive(visible && g.phase==7);if(visible && g.phase>=6){var at=TreasureHunt.Dig(g.site);treasureChest.anchoredPosition=ToBoard(at.X,at.Y);treasureChest.localScale=Vector3.one*sceneScale;var shape=treasureChest.GetComponent<TreasureShape>();shape.open=g.phase==7;shape.SetVerticesDirty();treasureEnding.anchoredPosition=ToBoard(at.X,at.Y)+new Vector2(0,-42)*sceneScale;treasureEnding.localScale=Vector3.one*sceneScale;}
   for(var i=0;i<3;i++){var npc=treasureFriends[i];npc.root.gameObject.SetActive(visible);if(!visible)continue;npc.visual.Select(g.friends[i]);var point=TreasureHunt.Friend(g,i,treasureClockRendered);var target=new Vector2(point.X,point.Y);var frame=treasureMotion[i].Step(target,"treasure/"+g.round+"/"+i,i==1,180,dt);var p=treasureNpcPoints[i]=treasureMotion[i].Point;npc.root.anchoredPosition=ToBoard(p.x,p.y);npc.root.localScale=Vector3.one*sceneScale*.8f;var pose=frame.Speed>1?frame.Pose:g.phase==7?CharacterPose.Dance:i==2 && g.phase==4?CharacterPose.Wave:i==1?CharacterPose.Carry:CharacterPose.Idle;npc.visual.PresentNpcFrame(new CharacterFrame(pose,frame.Speed,frame.FaceLeft,(float)(g.clock-g.started),frame.Travel,frame.ResetMotion),dt,.8f);}
   treasureTeacher.gameObject.SetActive(visible);if(visible){var at=TreasureHunt.Point(g,TreasureHunt.Next(g));var target=new Vector2(Mathf.Clamp(at.X+300,300,4620),440);var teacherFrame=treasureTeacherLocomotion.Step(target,"treasure/"+g.round,false,180,dt);treasureTeacherPoint=treasureTeacherLocomotion.Point;treasureTeacher.anchoredPosition=ToBoard(treasureTeacherPoint.x,treasureTeacherPoint.y);treasureTeacher.localScale=Vector3.one*sceneScale*.8f;var pose=teacherFrame.Pose==CharacterPose.Walk?0:g.phase==7?3:1;treasureTeacherWalk.Present(teacherFrame,pose,dt,.8f);}
   treasureMap.localScale=Vector3.one*Mathf.Min(safe.rect.width/930,safe.rect.height/500);for(var i=0;i<3;i++)treasureMapMarks[i].gameObject.SetActive(g!=null && g.phase>=5 && g.site==i);if(treasureMap.gameObject.activeSelf){if(own)treasureMap.SetAsLastSibling();else treasureMap.gameObject.SetActive(false);}
   if(!own){treasureSpoken=-1;treasureApproach="";return;}
   if(treasureRound!=g.round){treasureRound=g.round;treasureMystery=false;treasureSpoken=-1;treasureDemoAt=-11;}
   treasureHint.text=treasureMystery?TreasureHunt.MysteryClue(g):TreasureHunt.PictureClue(g);treasureClue.gameObject.SetActive(!treasureMystery);treasureClue.kind=g.phase==3?"pot":g.phase==4?"chimes":g.phase==5?new[]{"palm","flowers","lookout"}[g.site]:g.phase>=6?"map":"shell";treasureClue.special=true;treasureClue.symbol=g.phase==5?g.site:0;treasureClue.SetVerticesDirty();
   var pieces=g.phase>=5?3:g.phase>=4?2:g.phase>=3?1:0;treasureProgress.text="Our map · "+pieces+" / 3 pieces";for(var i=0;i<3;i++){treasurePieces[i].gameObject.SetActive(i<pieces);treasurePieces[i].symbol=g.tune[i];treasurePieces[i].SetVerticesDirty();}
   for(var i=0;i<3;i++){var icon=treasureActionIcons[i];var label=treasureActionLabels[i];treasureActions[i].interactable=g.phase>=2 && g.phase<=6;icon.special=false;icon.count=3;
    if(g.phase==2 || g.phase==3){var index=i+(g.phase==2?0:3);var correct=index==(g.phase==2?g.shell:3+g.pot);icon.kind=g.phase==2?"shell":"pot";icon.special=correct;icon.count=correct?3:i==2?2:1;label.text=correct && g.lifted[index]?"Take map piece":"Lift "+(g.phase==2?"shell ":"pot ")+(i+1);}
    else if(g.phase==4){icon.kind="symbol";icon.symbol=i;label.text=TreasureHunt.Symbol(i)+(g.tuneStep>0 && i==g.tune[g.tuneStep-1]?" ✓":"");}
    else if(g.phase==5){icon.kind="symbol";icon.symbol=i;label.text="Dig "+TreasureHunt.Landmark(i);}
    else if(g.phase==6){icon.kind="symbol";icon.symbol=g.wheels[i];label.text="Lock "+(i+1)+": "+TreasureHunt.Symbol(g.wheels[i]);}
    else{icon.kind=new[]{"compass","symbol","boat"}[i];icon.symbol=2;label.text=new[]{"Golden compass","Sparkly stars","Little boat"}[i];}icon.SetVerticesDirty();
   }
   treasureActionLabels[3].text=g.phase==6?"Open chest":g.phase==7?"New hunt":g.phase==4?"Hear the tune":"Explore together";treasureActions[3].interactable=g.phase==4 || g.phase>=6;
   if(treasureSpoken!=g.phase){treasureSpoken=g.phase;Narration.Stop();SpeakTreasure();}
   if(g.demoAt!=treasureDemoAt){treasureDemoAt=g.demoAt;treasureDemoNote=-1;var voice=Narration.GetComponent<AudioSource>();treasureDemoStartAt=Time.unscaledTime+(voice!=null && voice.isPlaying?Mathf.Max(0,voice.clip.length-voice.time):0)+.3f;}
   var elapsed=Time.unscaledTime-treasureDemoStartAt;var note=elapsed<0?-1:(int)(elapsed/.8f);
   foreach(var icon in treasureActionIcons)icon.rectTransform.localScale=Vector3.one*.48f;var chime=treasureChimes.GetComponent<TreasureShape>();chime.pulse=g.phase==4 && note>=0 && note<3?g.tune[note]:-1;chime.SetVerticesDirty();
   if(g.phase==4 && g.demoAt>=0 && note>=0 && note<3){var icon=treasureActionIcons[g.tune[note]];icon.rectTransform.localScale=Vector3.one*.65f;if(note!=treasureDemoNote){treasureDemoNote=note;if(treasureNotes[g.tune[note]]!=null)treasureTone.PlayOneShot(treasureNotes[g.tune[note]]);}}

  }
  private void AddTreasureDepth(Action<RectTransform,float,int,string> add){foreach(var s in treasureCovers.Concat(treasureFinds).Concat(treasureMounds))if(s.gameObject.activeSelf)add(s.rectTransform,s.rectTransform.anchoredPosition.y-20*sceneScale,2,s.name);foreach(var n in treasureFriends)if(n.root.gameObject.activeSelf)add(n.root,n.root.anchoredPosition.y,3,n.root.name);if(treasureChest?.gameObject.activeSelf==true)add(treasureChest,treasureChest.anchoredPosition.y,2,"treasure-chest");if(treasureChimes?.gameObject.activeSelf==true)add(treasureChimes,treasureChimes.anchoredPosition.y,2,"windchimes");if(treasureTeacher?.gameObject.activeSelf==true)add(treasureTeacher,treasureTeacher.anchoredPosition.y,3,"treasure-calypso");if(treasureEnding?.gameObject.activeSelf==true)add(treasureEnding,treasureEnding.anchoredPosition.y,3,"treasure-toys");}
  private void ResetTreasure(){treasureHud=treasureBelt=treasureOpening=treasureChest=treasureChimes=treasureEnding=treasureTeacher=null;treasureTeacherPoint=Vector2.zero;treasureClockRendered=0;treasurePresentationClock.Reset();treasureTeacherLocomotion.Reset();treasureCovers.Clear();treasureFinds.Clear();treasureMounds.Clear();treasurePieces.Clear();treasureActions.Clear();treasureActionIcons.Clear();treasureActionLabels.Clear();treasureFriends.Clear();treasureNpcPoints.Clear();treasureMotion.Clear();treasureMapMarks.Clear();treasureMap=null;treasureApproach="";treasureSending=false;treasureSpoken=treasureRound=treasureFrame=-1;foreach(var c in treasureAudio)if(c!=null)Resources.UnloadAsset(c);treasureAudio.Clear();}
 }
}
