<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net9.0</TargetFramework><NuGetAudit>false</NuGetAudit></PropertyGroup><ItemGroup><Compile Include="../../../Unity/FamilyPlayset/Assets/FamilyPlayset/Code/Core/**/*.cs" Link="Core/%(Filename)%(Extension)" /><Compile Include="../../../Unity/FamilyPlayset/Assets/FamilyPlayset/Code/Client/Worlds/Daycare/SandScoopFeedback.cs" Link="Client/SandScoopFeedback.cs" /><Compile Include="../../../Unity/FamilyPlayset/Assets/FamilyPlayset/Code/Client/Worlds/Daycare/SandWaterFeedback.cs" Link="Client/SandWaterFeedback.cs" /><Compile Include="../../../Unity/FamilyPlayset/Assets/FamilyPlayset/Code/Client/Worlds/Daycare/SandTipFeedback.cs" Link="Client/SandTipFeedback.cs" /><Compile Include="../../../Unity/FamilyPlayset/Assets/FamilyPlayset/Code/Client/Worlds/Daycare/SandDecorationFeedback.cs" Link="Client/SandDecorationFeedback.cs" /></ItemGroup></Project>
