"""Render the saved research as a local HTML guide; remote portraits stay remote.

Run: uv run --with markdown python docs/bluey-research/build_guide.py
"""
from pathlib import Path
import html
import json
import math
import re
import markdown

ROOT = Path(__file__).resolve().parent.parent
BASE = "bluey-game-research-2026-09-23"
refs = json.loads((ROOT / "bluey-research/character-references.json").read_text(encoding="utf-8"))
source = (ROOT / f"{BASE}.md").read_text(encoding="utf-8")
md = markdown.Markdown(extensions=["tables", "fenced_code", "toc"], extension_configs={"toc": {"toc_depth": "2-2"}})
body = md.convert(source)
body = re.sub(r"<h1.*?</h1>", "", body, count=1, flags=re.S)
body = body.replace("<table>", '<div class="table-scroll" tabindex="0" role="region" aria-label="Research table"><table>')
body = body.replace("</table>", "</table></div>")

cards = []
for c in refs:
    if not c.get("portrait"):
        continue
    name = html.escape(c["name"])
    note = "Three separate avatars planned" if c["name"] == "The Terriers" else "Head reference only" if c["name"] == "Lulu" else html.escape(c["group"])
    cards.append(f'''<a class="character" href="{html.escape(c['source'], quote=True)}" target="_blank" rel="noopener noreferrer" data-name="{name.lower()}">
      <div class="portrait"><img loading="lazy" decoding="async" src="{html.escape(c['portrait'], quote=True)}" alt="{name}, official character reference" width="180" height="165"><span class="image-fallback" hidden>Open official picture ↗</span></div>
      <strong>{name}</strong><small>{note}</small><span class="source-link">Official reference ↗</span></a>''')

stages = [
    {"name":"Heeler Home", "esName":"La casa", "icon":"🏠", "color":"#ffe1aa", "free":"Cooking, science, dinosaurs, talking books, personal bedrooms, and secret plush rooms.", "easy":"Put a cup on the table.", "explorer":"Set out two cups, pour pretend tea, and bring a snack.", "esEasy":"Pon una taza en la mesa.", "esExplorer":"Coloca dos tazas, sirve el té de juguete y trae algo para comer.", "rule":"Place → fill → serve"},
    {"name":"Backyard Garden", "esName":"El jardín", "icon":"🌻", "color":"#d5edba", "free":"Water flowers, move toys, play with balloons, and explore the sandpit.", "easy":"Pour a ready-filled bucket on the flower.", "explorer":"Fill your bucket at the tap, then water three plants.", "esEasy":"Riega la flor con el cubo lleno.", "esExplorer":"Llena el cubo en el grifo y riega tres plantas.", "rule":"Fill → pour → grow"},
    {"name":"Playground & Park", "esName":"El parque", "icon":"🛝", "color":"#f8d6c8", "free":"Working swings, slide, seesaw, climbing, tag, hide-and-seek, picnics, and your own play trail.", "easy":"Put a ball in the basket.", "explorer":"Find three picture-matched balls and put them in their baskets.", "esEasy":"Pon una pelota en la cesta.", "esExplorer":"Busca tres pelotas que coincidan con los dibujos y ponlas en sus cestas.", "rule":"Pick up → match → place"},
    {"name":"The Creek", "esName":"El arroyo", "icon":"⛵", "color":"#c7e6eb", "free":"Collect and stack rocks, fish, cross a log, float boats, and discover little creatures.", "easy":"Put a paper boat in the water.", "explorer":"Give your boat a leaf passenger and guide it to the landing.", "esEasy":"Pon un barquito de papel en el agua.", "esExplorer":"Sube una hoja al barquito y guíalo hasta la orilla.", "rule":"Attach → float → deliver"},
    {"name":"The Beach", "esName":"La playa", "icon":"🐚", "color":"#f5e5b3", "free":"Collect shells, build castles, startle seagulls, watch waves, and play ball or flying disc.", "easy":"Lift a filled mould to reveal a sandcastle.", "explorer":"Mix sand with a little water, make a castle, and add a shell.", "esEasy":"Levanta el molde lleno para descubrir un castillo de arena.", "esExplorer":"Mezcla arena con un poco de agua, haz un castillo y añade una concha.", "rule":"Fill → mould → decorate"},
    {"name":"Daycare", "esName":"La guardería", "icon":"🎨", "color":"#e5d9f5", "free":"Meet the whole cast, choose a playful lesson, join an optional pretend day, or step into an imagination story.", "easy":"Give one friend a plate.", "explorer":"Count the friends, set their places, then choose a story and a role together.", "esEasy":"Dale un plato a un amigo.", "esExplorer":"Cuenta a los amigos, prepara sus lugares y elijan una historia y un papel para jugar.", "rule":"Choose → imagine → play"},
]
buttons = []
for i, s in enumerate(stages):
    # Clockwise, starting at the top of a spacious circle.
    angle = math.radians(-90 + i * (360 / len(stages)))
    x, y = 50 + 33 * math.cos(angle), 50 + 33 * math.sin(angle)
    buttons.append(f'<button class="stage" data-stage="{i}" aria-pressed="{str(i == 1).lower()}" style="left:{x:.2f}%;top:{y:.2f}%;--bubble:{s["color"]}"><span aria-hidden="true">{s["icon"]}</span><strong>{html.escape(s["name"])}</strong></button>')

template = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>A Bluey playset for your iPads — research & picture board</title>
<style>
:root{--ink:#203e52;--blue:#23658e;--muted:#5d7482;--cream:#fcfaf5;--line:#d9e4e8;--sky:#e8f3fa;--accent:#f1b968}
*{box-sizing:border-box}html{scroll-behavior:auto;scroll-padding-top:82px}body{margin:0;background:var(--cream);color:var(--ink);font:17px/1.65 "Segoe UI",Arial,sans-serif}a{color:var(--blue);text-underline-offset:3px}a:hover{color:#144163}button,input{font:inherit}button{cursor:pointer}button:focus-visible,a:focus-visible,input:focus-visible,.table-scroll:focus-visible{outline:3px solid #bc6318;outline-offset:4px}h1,h2,h3{line-height:1.2;letter-spacing:-.025em}p{margin:0 0 1.2em}h2{font-size:30px;margin:0 0 20px}h3{font-size:23px;margin:30px 0 15px}small{font-size:13px}strong{font-weight:650}
.topbar{position:sticky;top:0;z-index:10;background:#fcfaf5f5;backdrop-filter:blur(8px);border-bottom:1px solid var(--line);padding:13px max(24px,calc((100vw - 1280px)/2));display:flex;align-items:center;gap:26px;flex-wrap:wrap;font-size:14px}.brand{font-weight:750;letter-spacing:.03em;margin-right:auto;text-decoration:none}.topbar nav{display:flex;gap:24px;flex-wrap:wrap}.topbar nav a{text-decoration:none}.wrap{max-width:1280px;margin:auto;padding:0 30px}
.hero{display:grid;grid-template-columns:1.2fr 1fr;align-items:center;min-height:400px;gap:34px;padding-top:54px;padding-bottom:44px}.eyebrow{font-size:12px;letter-spacing:.15em;font-weight:750;text-transform:uppercase;color:var(--blue);margin-bottom:16px}.hero h1{font-size:clamp(38px,4.4vw,61px);max-width:710px;margin:0 0 20px}.intro{max-width:620px;font-size:19px;color:var(--muted)}.tags{display:flex;gap:9px;flex-wrap:wrap}.tag{border-radius:24px;background:#e7f0f1;font-size:12px;font-weight:650;padding:5px 12px}.hero-art{height:335px;position:relative;background:#ddecf3;border-radius:48% 52% 40% 60%;overflow:hidden;display:flex;align-items:flex-end;justify-content:center;gap:6px;padding:22px 24px 0}.hero-art img{height:95%;width:48%;object-fit:contain;object-position:bottom}.hero-art img:last-child{height:78%}.hero-art:before{content:"LET’S PLAY";position:absolute;top:29px;right:80px;font-size:12px;font-weight:750;letter-spacing:.17em;color:#5686a1;transform:rotate(9deg)}
.note{background:#fff2d9;border-left:4px solid #e3af52;padding:16px 20px;border-radius:0 12px 12px 0;font-size:15px;margin:16px 0 30px}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-bottom:60px}.summary article{border-top:2px solid #8ab1c7;padding:20px 0}.summary h3{font-size:20px;margin:0 0 10px}.summary p{font-size:15px;color:var(--muted);margin:0}.section{padding:52px 0;border-top:1px solid var(--line)}.section-lead{max-width:780px;color:var(--muted)}
.stage-layout{display:grid;grid-template-columns:minmax(400px,1.1fr) minmax(280px,.9fr);gap:36px;align-items:center}.wheel{width:100%;aspect-ratio:1;max-width:590px;position:relative;margin:auto;background:radial-gradient(circle at center,#fff 0 28%,#eef3ee 28% 29%,transparent 29%)}.stage{position:absolute;transform:translate(-50%,-50%);width:27%;aspect-ratio:1;border:5px solid transparent;border-radius:50%;background:var(--bubble);box-shadow:0 5px 0 #0000000a;display:flex;flex-direction:column;align-items:center;justify-content:center;line-height:1.1;gap:7px;padding:10px;transition:transform .16s,border-color .16s}.stage>span{font-size:clamp(30px,4vw,47px);line-height:1.1}.stage strong{font-size:13px;max-width:100px}.stage[aria-pressed=true]{border-color:var(--blue);transform:translate(-50%,-50%) scale(1.06)}.stage:hover{box-shadow:0 6px 16px #203e5220}.wheel-center{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:34%;text-align:center;line-height:1.3}.wheel-center span{font-size:10px;letter-spacing:.12em;color:var(--muted);text-transform:uppercase}.wheel-center strong{display:block;font-size:19px;margin-top:8px}.quest-preview{background:white;border:1px solid var(--line);border-radius:24px;padding:30px;box-shadow:0 10px 35px #25455806}.quest-preview h3{font-size:29px;margin:7px 0 14px}.quest-preview p{font-size:16px}.control-row{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.control-row .label{width:76px;font-size:12px;color:var(--muted)}.toggle{border:1px solid var(--line);border-radius:10px;padding:6px 13px;background:white;font-size:13px}.toggle[aria-pressed=true]{color:white;background:var(--blue);border-color:var(--blue)}.prompt{background:var(--sky);border-radius:14px;padding:20px;margin-top:20px}.prompt .label{font-size:11px;letter-spacing:.12em;text-transform:uppercase;color:var(--blue);font-weight:700}.prompt p{font-size:20px;line-height:1.45;margin:8px 0 0}.recipe{font-size:13px;color:var(--muted);border-top:1px solid var(--line);margin-top:22px;padding-top:14px}.demo-disclaimer{font-size:13px;color:var(--muted);margin-top:15px}
.gallery-tools{display:flex;align-items:center;justify-content:space-between;gap:20px;flex-wrap:wrap;margin:24px 0}.gallery-tools input{padding:11px 15px;border:1px solid #bacbd2;border-radius:12px;background:white;width:min(330px,100%);font-size:15px}.gallery-count{font-size:13px;color:var(--muted)}.characters{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:16px}.character{display:flex;flex-direction:column;text-align:center;text-decoration:none;color:var(--ink);background:white;border:1px solid var(--line);border-radius:20px;padding:14px 10px 17px;min-width:0;transition:transform .15s}.character:hover{transform:translateY(-4px);border-color:#89b6cf}.portrait{height:164px;display:grid;place-items:center;background:#f2f7fa;border-radius:14px;margin-bottom:13px}.portrait img{width:100%;height:155px;object-fit:contain}.character strong{font-size:17px}.character small{font-size:11px;color:var(--muted);line-height:1.3;margin:5px 0;min-height:29px}.source-link{font-size:11px;color:var(--blue)}.character[hidden]{display:none}.image-fallback{font-size:12px;color:var(--muted)}
.report-layout{display:grid;grid-template-columns:230px minmax(0,1fr);gap:48px;align-items:start}.contents{position:sticky;top:91px;max-height:calc(100vh - 120px);overflow:auto;font-size:12px;line-height:1.6;padding-right:8px}.contents h3{font-size:13px;text-transform:uppercase;letter-spacing:.09em;margin:0 0 15px}.contents ul{list-style:none;padding:0;margin:0}.contents li{margin:0 0 11px}.contents a{text-decoration:none;color:var(--muted)}.contents a:hover{color:var(--blue)}.report{font-size:16px;min-width:0}.report>h2{font-size:28px;padding-top:40px;margin-top:42px;border-top:1px solid var(--line)}.report>h3{font-size:22px}.report li{margin-bottom:9px}.report ul,.report ol{padding-left:25px}.report .table-scroll{overflow-x:auto;margin:24px 0 30px;border:1px solid var(--line);border-radius:10px}.report table{border-collapse:collapse;width:100%;font-size:13px;line-height:1.55}.report th{background:#e8f1f5;text-align:left;color:#274d66}.report th,.report td{padding:13px 15px;border-bottom:1px solid var(--line);vertical-align:top;min-width:100px}.report tr:last-child td{border-bottom:0}.report tr:nth-child(even) td{background:#ffffff75}.report code{font-size:.88em;background:#e9eef0;border-radius:4px;padding:2px 5px;overflow-wrap:anywhere}.report a{overflow-wrap:anywhere}.footer{padding:35px 0 50px;border-top:1px solid var(--line);font-size:13px;color:var(--muted);margin-top:50px}.footer a{margin-right:20px}
@media(min-width:1450px){.stage strong{font-size:14px}.stage>span{font-size:49px}}
@media(max-width:1000px){.characters{grid-template-columns:repeat(4,minmax(0,1fr))}.hero{grid-template-columns:1.3fr 1fr}.hero-art{height:280px}.stage-layout{gap:18px;grid-template-columns:1fr 1fr}.stage strong{font-size:11px}.quest-preview{padding:22px}.report-layout{grid-template-columns:190px minmax(0,1fr);gap:26px}}
@media(max-width:760px){.topbar{padding:11px 20px;gap:12px}.brand{font-size:12px}.topbar nav{gap:15px;font-size:12px}.wrap{padding:0 20px}.hero{padding-top:35px;grid-template-columns:1fr;gap:22px}.hero h1{font-size:43px}.hero-art{height:250px;max-width:400px;width:100%;margin:auto}.summary{grid-template-columns:1fr;gap:5px;margin-bottom:20px}.summary article{padding:16px 0}.stage-layout{grid-template-columns:1fr;gap:20px}.wheel{max-width:530px}.stage>span{font-size:40px}.stage strong{font-size:12px}.section{padding:38px 0}.characters{grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.portrait{height:135px}.portrait img{height:128px}.character strong{font-size:15px}.character{padding:9px 7px 13px}.report-layout{display:block}.contents{position:static;max-height:none;border:1px solid var(--line);border-radius:16px;padding:22px;margin-bottom:35px}.contents ul{columns:2}.report{font-size:15px}.report>h2{font-size:25px}.report th,.report td{padding:10px;min-width:140px}h2{font-size:28px}}
@media(max-width:430px){.characters{grid-template-columns:repeat(2,minmax(0,1fr))}.topbar nav{gap:10px}.hero h1{font-size:37px}.stage>span{font-size:30px}.stage strong{font-size:10px}.wheel-center strong{font-size:15px}.wheel-center span{font-size:8px}.stage{padding:5px;border-width:3px}.contents ul{columns:1}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
@media print{.topbar,.contents,.gallery-tools,.control-row{display:none}.hero{min-height:0}.hero-art{height:200px}.wrap{max-width:none;padding:0}.stage-layout{grid-template-columns:1fr 1fr}.wheel{max-width:420px}.characters{grid-template-columns:repeat(5,1fr)}.character{break-inside:avoid}.report-layout{display:block}.report table{font-size:10px}.table-scroll{overflow:visible!important}.report th,.report td{min-width:0}.section{break-before:page}.footer{margin-top:20px}body{font-size:11pt;background:white}}
</style></head><body>
<header class="topbar"><a class="brand" href="#top">THE FAMILY PLAYSET</a><nav aria-label="Guide navigation"><a href="family-playset-build-guide-2026-09-23.html">Build guide</a><a href="family-playset-package-research-2026-09-23.html">Packages</a><a href="family-playset-technical-research-2026-09-23.html">Technical research</a><a href="family-playset-feasibility-audit-2026-09-23.html">Feasibility audit</a><a href="#places">Six worlds</a><a href="#characters">Characters</a><a href="#research">Research</a></nav></header>
<main id="top" class="wrap">
<section class="hero"><div><p class="eyebrow">Bluey game research · 23 September 2026</p><h1>Little adventures.<br>A world to play in.</h1><p class="intro">A personal illustrated playset for your family: choose a friend, explore together, move things around, and discover what happens.</p><div class="tags"><span class="tag">Ages 3 & 6</span><span class="tag">1–4 family players</span><span class="tag">iPad · iPhone · Android</span><span class="tag">2D dollhouse</span><span class="tag">English first + Spanish</span></div></div>
<div class="hero-art" aria-label="Official Bluey and Bingo character references"><img src="https://www.bluey.tv/wp-content/uploads/2023/07/Bluey.png" alt="Bluey" width="250" height="320"><img src="https://www.bluey.tv/wp-content/uploads/2023/07/B2.png" alt="Bingo" width="220" height="270"></div></section>
<div class="summary"><article><h3>Make it in Unity 2D</h3><p>A fresh project with reusable touch and object rules. Blender is optional for this illustrated style.</p></article><article><h3>Shared play, with offline solo.</h3><p>The prototype connects automatically to the home PC. Your owned VPS is the next hosting target after server readiness. Full offline content and iPad hosting/recovery remain required work; travel co-op depends on connectivity.</p></article><article><h3>Let the characters speak</h3><p>Generate and review voice clips on your Windows PC, then include them in the game for offline play.</p></article></div>
<div class="note"><strong>New: simpler play and richer objects.</strong> The <a href="toca-piknik-interaction-research-2026-09-23.html">Toca Boca + Piknik research supplement</a> combines close-up Simple Play for your younger child with Explore &amp; Stories for your older child. Try its object explorer to see how one bucket, fruit, sponge, or ball can support several kinds of play.</div>
<div class="note" id="latest-features"><strong>Audit verdict: achievable, with important prototypes first.</strong> The <a href="family-playset-feasibility-audit-2026-09-23.html">complete feasibility audit</a> reviews all 51 sections and both supplements. <strong>iPad hosting, automatic joining and automatic host switching remain required.</strong> Only travel multiplayer is optional; complete offline solo stays required. Read the <a href="#52-feasibility-audit-and-current-priorities">current priorities and proof sequence</a>. This was the September 23 feasibility review. The <a href="family-playset-build-guide-2026-09-23.html#19-implementation-audit-and-remaining-work">September 25 implementation audit</a> records all 55 chapters and 35 goals: qualified Windows 90 recovery, last deployed PC/Samsung 83 and Apple 79, with unfinished work separated from passed proofs.</div>
<div class="note"><strong>Shared items find their way home.</strong> The goal is that <a href="#51-automatic-item-returns-stocked-areas-and-tidy-bedrooms">unused borrowed props return automatically</a> while personal decorations and saved creations stay protected. Build 83 implements timers for the garden tools and completed stations. The wider catalog, containers, protected creations, stocked stations and bedroom limits remain planned.</div>
<div class="note"><strong>One shared world, freedom to explore.</strong> Everyone can <a href="#50-one-shared-world-independent-travel-and-shared-items">travel independently and meet in the same existing area</a>. Leaving never pauses or moves the players who stay. A bucket held by one player is visible to everyone nearby and unavailable until released. Includes the creek/playground example, Unity design, and required tests. Windows proofs and scoped two-iPad travel/reunion feedback establish the prototype behavior; full mixed-device lifecycle, mobile-host and content acceptance remain open.</div>
<div class="note"><strong>Future hosting: your owned VPS.</strong> The <a href="#55-future-hosting-on-your-owned-vps">VPS plan</a> follows server reliability work and can precede finished content. It would support automatic family connections at home or over travel internet. Travel connectivity remains lower priority; required iPad hosting, automatic host switching, full offline solo and signing renewal remain. No VPS deployment has occurred.</div>
<div class="note"><strong>The whole family can join.</strong> Plan for <a href="#47-up-to-four-family-players-across-ipad-iphone-and-android">1–4 players across iPad, iPhone, and Android</a>, including your Galaxy S26 Ultra. Everyone may choose any available character, including Bandit and Chilli, and switch during play. See the <a href="#48-android-build-phone-layout-and-four-player-acceptance">phone build and four-player test plan</a>. All four physical devices were admitted together on build 79, with scoped play feedback. The complete character roster, sustained mixed-device qualification and iPad hosting remain planned.</div>
<div class="note"><strong>Open the app and connect automatically.</strong> The <a href="#44-automatic-family-connection-and-ipad-hosting">plan requires both iPads to host or join</a>, with foreground family discovery and no child-facing Host/Join setup. The <a href="#45-automatic-host-selection-recovery-and-save-reconciliation">recovery and reunion plan</a> covers host shutdown, offline branches, and keeping creations. <a href="#46-automatic-multiplayer-implementation-and-verification-plan">Device tests and implementation plan</a>. Native discovery, enrollment and PC-server admission have four-device evidence. Windows 90 adds complete checkpoints and separate saved adventures after outages; mobile qualification is pending. iPad hosting, automatic host switching and automatic branch reconciliation remain unbuilt.</div>
<div class="note"><strong>Outdoor adventures and Daycare.</strong> Explore <a href="#37-the-beach-collecting-building-and-playing-together">10 beach activities</a>, <a href="#38-the-creek-rocks-water-and-gentle-discovery">10 creek activities</a>, and <a href="#39-playground-and-park-equipment-that-really-works">12 park activities</a>. <a href="#40-daycare-a-sixth-world-with-an-optional-pretend-day">Daycare is the sixth world</a>: an optional pretend day, 2–3 rotating games, <a href="#41-daycare-learning-short-playful-and-spoken">12 learning stations</a>, and <a href="#42-the-imagination-mat-nine-stories-that-become-playable-worlds">nine imagination stories with spoken roles</a>. <a href="#43-building-saving-and-testing-the-outdoor-and-daycare-expansion">Build and acceptance plan</a>. Research and design only; game implementation is pending.</div>
<div class="note"><strong>Science, their own rooms, and road-trip play.</strong> Explore <a href="#30-a-simple-and-playful-science-corner">eight science activities</a>, <a href="#31-joining-and-leaving-without-restarting-play">joining and leaving anytime</a>, <a href="#32-two-personal-bedrooms-with-shared-updates">two synchronized bedrooms</a>, <a href="#33-secret-plush-rooms-with-stars-and-northern-lights">secret plush rooms with northern lights</a>, and <a href="#34-hide-and-seek-with-enterable-furniture-and-gentle-clues">closets, drawers, giggles, and parent-led hide-and-seek</a>. The <a href="#35-road-trip-play-hotspot-co-op-and-coming-home">travel plan</a> requires full offline play even when hotspot co-op is unavailable. <a href="#36-integration-milestones-and-acceptance-for-this-expansion">Build and device checks</a> keep every feature tracked as planned until tested.</div>
<div class="note"><strong>Books, TV, and a room full of dinosaurs.</strong> Open the plan for a <a href="#25-reading-nook-and-interactive-books">talking bookshelf</a>, <a href="#26-dinosaur-books-and-spoken-names">six proposed books and an eight-page dinosaur story</a>, a <a href="#27-tv-corner-and-local-video-library">TV clip library</a>, and <a href="#28-dinosaur-toy-room-and-discovery-mini-game">20 dinosaur toys plus the Discovery Mat mini-game</a>. Each child can read, watch, or play independently. The house content remains planned. A separate single-clip playback/bookmark fixture has passed scoped checks; the TV library is not built.</div>
<div class="note"><strong>More ways to play together.</strong> The <a href="#16-expanded-feature-tracker">main feature tracker</a> also covers changing characters during play, freely switching activities, cooking <a href="#19-kitchen-five-pizzas-five-cakes-five-meals">15 recipes</a>, fishing at the <a href="#20-the-water-feature-and-fishing-mini-game">backyard pond</a>, cleanup, roaming parents, and <a href="#22-hide-and-seek-and-parents-with-everyday-routines">hide-and-seek</a>. Browse <a href="#23-show-games-and-activities-catalog">32 show-inspired activity ideas</a> with simpler and deeper ways to play.</div>
<section class="section" id="places"><p class="eyebrow">Choose somewhere to play</p><h2>Six circles. Six little worlds.</h2><p class="section-lead">A clickable layout concept. Select a location and compare a simple invitation with a longer activity. All areas remain available for free play.</p>
<div class="stage-layout"><div class="wheel" aria-label="Six proposed locations">{{STAGE_BUTTONS}}<div class="wheel-center"><span>Selected area</span><strong id="center-name">Backyard Garden</strong></div></div>
<div class="quest-preview"><div class="eyebrow">Proposed activity</div><h3 id="stage-title">Backyard Garden</h3><p id="free-play"></p><div class="control-row" role="group" aria-label="Quest assistance"><span class="label">Assistance</span><button class="toggle" data-difficulty="easy" aria-pressed="true">Simple</button><button class="toggle" data-difficulty="explorer" aria-pressed="false">Explorer</button></div><div class="control-row" role="group" aria-label="Prompt language"><span class="label">Text preview</span><button class="toggle" data-locale="en" aria-pressed="true">English</button><button class="toggle" data-locale="es" aria-pressed="false">Español</button></div><div class="prompt" aria-live="polite"><span class="label">Spoken-line draft</span><p id="quest-line"></p></div><div class="recipe" id="recipe"></div><div class="demo-disclaimer">Research preview only. These controls change the example text; no game or generated voice is included yet.</div></div></div></section>
<section class="section" id="characters"><p class="eyebrow">A growing cast of friends</p><h2>Character picture board</h2><p class="section-lead">{{PORTRAIT_COUNT}} official portrait references, including Bandit, Chilli, the Terriers together, and three older children. Everyone can choose any available character. Tap a card for its source. The playable roster will use individual avatars and can expand for missing favorites.</p><div class="gallery-tools"><label><span class="sr-only">Find a character: </span><input id="character-search" type="search" placeholder="Bluey, Bingo, Rusty…" autocomplete="off"></label><span class="gallery-count" id="gallery-count">{{PORTRAIT_COUNT}} reference entries</span></div><div class="characters">{{CARDS}}</div><p id="no-results" hidden>No matching character in this reference set.</p><div class="note"><strong>Still to verify:</strong> Pretzel's official portrait. The Terriers need three separate game avatars; Lulu's current reference is a head portrait. These are reference pictures, not finished animation rigs. Images load from bluey.tv and require internet in this document.</div></section>
<section class="section" id="research"><p class="eyebrow">From idea to a reliable family game</p><h2>The complete research & build guide</h2><p class="section-lead">The main record: automatic item returns, stocked areas, protected creations, tidy bedrooms, independent travel within one shared world, exclusive shared items, remote home-PC hosting, private connection options, 1–4-player Android/iPad/iPhone cross-play, open character choice, automatic family connection, mobile hosting and recovery, outdoor activities, daycare, playful learning, imagination stories, science play, independent bedrooms, secret aurora rooms, flexible co-op, full offline travel, narrated books, TV, dinosaurs, cooking, hiding, show activities, sources, and device checks.</p><div class="report-layout"><aside class="contents"><h3>In this guide</h3>{{TOC}}</aside><article class="report">{{REPORT}}</article></div></section>
<footer class="footer"><p>Prepared for your family's iPads and phones. Research checked 23 September 2026; implementation status audited 25 September against local source and retained evidence. External sources were not freshly revalidated. Proposed designs are distinguished from source findings and untested integrations in the guide.</p><a href="bluey-game-research-2026-09-23.md">Editable Markdown report</a><a href="bluey-research/character-references.json">Character sources</a><a href="bluey-research/github-evidence.json">Repository evidence</a><a href="bluey-research/outdoors-daycare-evidence.json">Outdoor &amp; daycare sources</a><a href="bluey-research/automatic-multiplayer-evidence.json">Automatic multiplayer sources</a><a href="bluey-research/four-player-cross-platform-evidence.json">Four-player &amp; Android sources</a><a href="bluey-research/remote-home-server-evidence.json">Remote home-server sources</a><a href="bluey-research/shared-world-evidence.json">Shared-world sources</a><a href="bluey-research/item-return-evidence.json">Item-return sources</a><a href="ipad-game-research-2026-09-23.md">iPad build & renewal plan</a></footer>
</main>
<script>
const stages = {{STAGES_JSON}};
let selected = 1, difficulty = 'easy', locale = 'en';
function renderStage(){
 const stage = stages[selected];
 document.getElementById('center-name').textContent = locale === 'es' ? stage.esName : stage.name;
 document.getElementById('stage-title').textContent = stage.name;
 document.getElementById('free-play').textContent = stage.free;
 document.getElementById('quest-line').textContent = locale === 'es' ? stage[difficulty === 'easy' ? 'esEasy' : 'esExplorer'] : stage[difficulty];
 document.getElementById('quest-line').lang = locale;
 document.getElementById('recipe').textContent = 'Reusable interaction: ' + stage.rule;
 document.querySelectorAll('[data-stage]').forEach(b=>b.setAttribute('aria-pressed', Number(b.dataset.stage) === selected));
 document.querySelectorAll('[data-difficulty]').forEach(b=>b.setAttribute('aria-pressed', b.dataset.difficulty === difficulty));
 document.querySelectorAll('[data-locale]').forEach(b=>b.setAttribute('aria-pressed', b.dataset.locale === locale));
}
document.querySelectorAll('[data-stage]').forEach(b=>b.addEventListener('click',()=>{selected=Number(b.dataset.stage);renderStage()}));
document.querySelectorAll('[data-difficulty]').forEach(b=>b.addEventListener('click',()=>{difficulty=b.dataset.difficulty;renderStage()}));
document.querySelectorAll('[data-locale]').forEach(b=>b.addEventListener('click',()=>{locale=b.dataset.locale;renderStage()}));
document.getElementById('character-search').addEventListener('input',e=>{
 const q=e.target.value.toLocaleLowerCase().trim();let count=0;
 document.querySelectorAll('.character').forEach(c=>{c.hidden=!c.dataset.name.includes(q);if(!c.hidden)count++});
 document.getElementById('gallery-count').textContent=count+' reference '+(count===1?'entry':'entries');
 document.getElementById('no-results').hidden=count!==0;
});
document.querySelectorAll('.portrait img').forEach(img=>{
 const fallback=()=>{img.hidden=true;img.nextElementSibling.hidden=false};
 img.addEventListener('error',fallback);if(img.complete && !img.naturalWidth)fallback();
});
renderStage();
</script></body></html>'''

output = (template.replace("{{STAGE_BUTTONS}}", "\n".join(buttons))
          .replace("{{CARDS}}", "\n".join(cards))
          .replace("{{PORTRAIT_COUNT}}", str(len(cards)))
          .replace("{{TOC}}", md.toc)
          .replace("{{REPORT}}", body)
          .replace("{{STAGES_JSON}}", json.dumps(stages, ensure_ascii=False).replace("</", "<\\/")))
destination = ROOT / f"{BASE}.html"
destination.write_text(output, encoding="utf-8")
print(f"Created {destination}: {len(output):,} characters; {len(cards)} portrait entries; {len(stages)} location buttons")
