"""Render the Toca/Piknik research supplement and its interaction explorer.

Run: uv run --with markdown python docs/bluey-research/build_toca_guide.py
"""
from pathlib import Path
import json
import re
import markdown

ROOT = Path(__file__).resolve().parent.parent
BASE = "toca-piknik-interaction-research-2026-09-23"
source = (ROOT / f"{BASE}.md").read_text(encoding="utf-8")
md = markdown.Markdown(extensions=["tables", "fenced_code", "toc"], extension_configs={"toc": {"toc_depth": "2-2"}})
body = md.convert(source)
body = re.sub(r"<h1.*?</h1>", "", body, count=1, flags=re.S)
body = body.replace("<table>", '<div class="table-scroll" tabindex="0" role="region" aria-label="Research table"><table>').replace("</table>", "</table></div>")
existing = (ROOT / "bluey-game-research-2026-09-23.html").read_text(encoding="utf-8")
style = re.search(r"<style>(.*?)</style>", existing, re.S).group(1)

toys = [
 {"id":"bucket","icon":"🪣","name":"Bucket","identity":"A container with lots of possible destinations.","actions":[
  {"name":"Fill","target":"🚰 Tap","result":"The bucket fills. Its waterline rises, it gets a little heavier-looking, and you hear a splash.","simple":"Drag the bucket into the wide tap zone; filling finishes automatically.","explore":"Hold under the tap for a partial fill, then carry the same water elsewhere.","change":"Empty → holding water","next":"Pour into a cup, tray, plant, or sand mould."},
  {"name":"Water","target":"🌻 Plant","result":"Water leaves the bucket and the plant perks up. Bingo can say, ‘A drink for our flower!’","simple":"Drop over the large plant highlight; the game handles the pouring pose.","explore":"Use the same drop action or hold to pour a smaller amount for a longer gardening activity.","change":"Bucket loses water → plant gains moisture","next":"Move the watered pot or decorate it."},
  {"name":"Float","target":"⛵ Water tray","result":"The tray fills and a paper boat bobs on its surface. The child can give it a leaf passenger.","simple":"A broad tray target catches the pour; a boat is already nearby.","explore":"Choose the amount, add decorations, and guide the boat to a landing.","change":"Empty tray → water tray → floating boat","next":"Scoop water back out or retrieve the boat."},
  {"name":"Build","target":"🏖️ Sand mould","result":"Dry sand becomes damp enough to form a castle. Lift the mould and keep decorating the result.","simple":"One assisted pour and one big lift action reveal the shape.","explore":"Fill the mould, add water, lift, decorate, wash, and rebuild.","change":"Dry sand → wet sand → formed castle","next":"Add shells or wash the castle down."}]},
 {"id":"fruit","icon":"🍓","name":"Fruit","identity":"An ingredient that stays useful as it changes.","actions":[
  {"name":"Slice","target":"🔪 Prep board","result":"The fruit becomes a small, bounded set of pieces that can still be picked up and used.","simple":"Drop onto the prep board and tap a large chop picture.","explore":"Choose whole or sliced ingredients and arrange the pieces.","change":"Whole fruit → prepared pieces","next":"Plate, blend, carry, or offer a piece."},
  {"name":"Blend","target":"🥤 Blender","result":"The ingredients become a visible colored drink, with a short motor sound and optional foam.","simple":"A wide opening accepts fruit, followed by one large start button.","explore":"Try different fruit combinations, then choose cups and pour amounts.","change":"Ingredients consumed → mixture created once","next":"Pour the mixture into a cup."},
  {"name":"Serve","target":"🍽️ Plate","result":"The fruit sits on the plate. The plate and its contents can travel together.","simple":"Generous placement slots keep the food from sliding away.","explore":"Arrange a snack plate and carry it to a picnic blanket.","change":"Loose ingredient → contained ingredient","next":"Carry, eat, rearrange, or wash the empty plate."},
  {"name":"Taste","target":"🙂 Character","result":"A character takes a bite and makes a short, playful face or voice response. It is not a grade.","simple":"Use a large mouth/hand target with one clear eating response.","explore":"Compare reactions to different prepared foods and drinks.","change":"Food amount decreases → reaction event","next":"Try another combination or make a meal."}]},
 {"id":"sponge","icon":"🧽","name":"Sponge","identity":"A tool that makes mistakes part of the play.","actions":[
  {"name":"Soak","target":"💧 Puddle","result":"The puddle shrinks while the sponge visibly becomes wet.","simple":"A broad swipe covers enough area to show immediate progress.","explore":"Clean part of a spill, then squeeze the collected water elsewhere.","change":"Puddle water → sponge water","next":"Squeeze into a container or drain."},
  {"name":"Wash","target":"🚗 Toy car","result":"Dirt disappears under the sponge and bubbles appear along its path.","simple":"Large strokes quickly reveal the clean toy.","explore":"Create a wash-and-park station and clean different toys.","change":"Dirty surface → clean surface","next":"Roll the clean car or get it muddy again."},
  {"name":"Squeeze","target":"🪣 Bucket","result":"A short stream carries the sponge's stored water into the bucket. It cannot create extra water.","simple":"Drop the wet sponge over the bucket to squeeze automatically.","explore":"Choose a container or drain, with a visible remaining amount.","change":"Wet sponge → drained sponge + transferred water","next":"Use the sponge again or pour the collected water."},
  {"name":"Undo paint","target":"🎨 Painted pot","result":"Washable paint fades where the sponge moves, making room for another design.","simple":"Broad cleaning strokes and an easy whole-surface clean option.","explore":"Remove part of a design and paint something different.","change":"Painted surface → editable clean area","next":"Paint, decorate, and wash again."}]},
 {"id":"ball","icon":"⚽","name":"Ball","identity":"A familiar toy that connects to the environment.","actions":[
  {"name":"Roll","target":"📐 Ramp","result":"The ball rolls along the ramp with a readable bounce and soft sound.","simple":"Drop near the ramp's start; assistance places it on the surface.","explore":"Move the ramp and see how it changes the rolling path.","change":"Placed ball → moving ball","next":"Catch, retrieve, or aim toward a basket."},
  {"name":"Basket","target":"🧺 Basket","result":"The ball settles inside and the basket visibly holds it.","simple":"A wide target and forgiving snap make placement easy.","explore":"Sort or carry several toys as part of a pretend cleanup game.","change":"Loose ball → basket contents","next":"Take it out or carry the basket."},
  {"name":"Float","target":"💦 Tray","result":"A buoyant ball bobs gently; the same water tray also accepts the paper boat.","simple":"Drop anywhere within a broad water region.","explore":"Compare designated floatable and non-floatable toys.","change":"Dry placement → supported on water","next":"Scoop the ball out or move it with the boat."},
  {"name":"Wash","target":"🧽 Sponge","result":"A muddy ball becomes clean. Washing follows the same rule already learned with the toy car.","simple":"Large strokes reveal the clean pattern.","explore":"Make a pretend toy-washing station with several objects.","change":"Dirty ball → clean ball","next":"Play, decorate the scene, or get it muddy again."}]}
]

template = r'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Toca + Piknik — interactive objects for our Bluey game</title><style>{{STYLE}}
.supp-hero{padding:65px 0 35px;max-width:940px}.supp-hero h1{font-size:clamp(38px,5vw,62px);margin:0 0 24px;max-width:890px}.supp-hero .intro{max-width:820px}.combine{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin:24px 0 42px}.combine>div{padding:24px;border-radius:20px;background:#e9f2f6}.combine>div:nth-child(2){background:#edf0df}.combine>div:nth-child(3){background:#f7e8d9}.combine strong{display:block;font-size:21px;margin-bottom:8px}.combine p{font-size:15px;margin:0;color:var(--muted)}.lab{border:1px solid var(--line);border-radius:26px;background:white;padding:28px;margin:26px 0 30px}.mode-row{display:flex;align-items:center;justify-content:space-between;gap:18px;flex-wrap:wrap}.mode-row p{font-size:13px;color:var(--muted);margin:0}.mode-row .controls{display:flex;gap:8px;flex-wrap:wrap}.toy-row{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:27px 0}.toy{display:flex;flex-direction:column;align-items:center;gap:7px;padding:17px 8px;background:#f5f8f9;border:2px solid transparent;border-radius:17px;color:var(--ink)}.toy .emoji{font-size:37px;line-height:1.2}.toy[aria-pressed=true]{border-color:var(--blue);background:var(--sky)}.lab-body{display:grid;grid-template-columns:.9fr 1.1fr;gap:25px;align-items:start}.identity{padding:25px;border-radius:18px;background:#fcf5e7}.identity h3{margin:0 0 12px;font-size:24px}.identity p{font-size:15px}.action-row{display:flex;flex-wrap:wrap;gap:8px}.action{border:1px solid #c2d2da;background:white;border-radius:12px;padding:10px 14px;font-size:14px;color:var(--ink)}.action[aria-pressed=true]{background:var(--blue);color:white;border-color:var(--blue)}.outcome{background:#f1f7f5;border-radius:18px;padding:25px;min-height:330px}.outcome .target{font-size:25px;font-weight:650;line-height:1.3;margin-bottom:15px}.outcome .result{font-size:17px;line-height:1.6}.outcome .change{font-size:13px;padding:12px 0;border-top:1px solid #d7e2df;border-bottom:1px solid #d7e2df}.outcome .next{font-size:14px;margin:16px 0 0}.gesture{margin:20px 0 0;padding:16px;background:white;border-radius:12px;font-size:14px}.gesture strong{display:block;margin-bottom:5px}.lab-note{font-size:12px;color:var(--muted);margin:20px 0 0}.mini-path{padding:24px 28px;border-radius:18px;background:#edf0df;margin:20px 0 45px;font-size:18px;line-height:1.8}.mini-path strong{display:block;font-size:12px;text-transform:uppercase;letter-spacing:.12em;margin-bottom:8px}.supp-report{padding-top:30px}
@media(max-width:760px){.supp-hero{padding-top:38px}.combine{grid-template-columns:1fr;gap:10px}.combine>div{padding:19px}.lab{padding:18px}.lab-body{grid-template-columns:1fr;gap:15px}.toy-row{gap:6px}.toy{padding:13px 5px;font-size:12px}.toy .emoji{font-size:30px}.identity,.outcome{padding:20px}.mode-row .controls{width:100%}.mode-row .toggle{flex:1;font-size:12px}.supp-hero h1{font-size:38px}.mini-path{padding:20px;font-size:16px}.topbar nav{gap:12px}}
</style></head><body><header class="topbar"><a class="brand" href="bluey-game-research-2026-09-23.html">THE FAMILY PLAYSET</a><nav aria-label="Research navigation"><a href="#object-lab">Try the ideas</a><a href="#research">Research</a></nav></header><main class="wrap">
<section class="supp-hero"><p class="eyebrow">Toca Boca + Piknik · Research supplement</p><h1>Make every toy<br>an invitation to play.</h1><p class="intro">A simpler way in for your three-year-old. More combinations for your six-year-old. One Bluey world where the objects remember what you do to them.</p><div class="tags"><span class="tag">Direct touch</span><span class="tag">Connected interactions</span><span class="tag">Shared world</span><span class="tag">Speaking characters</span></div></section>
<div class="combine"><div><strong>Toca Boca World</strong><p>Connected places, movable belongings, and room to invent a story.</p></div><div><strong>Toca Boca Jr</strong><p>Focused activities with a small set of tools and visible transformations.</p></div><div><strong>Sago Mini / Piknik</strong><p>Close-up play, forgiving actions, expressive reactions, and little surprises.</p></div></div>
<section class="section" id="object-lab"><p class="eyebrow">Explore our proposed object rules</p><h2>One object. Several things to try.</h2><p class="section-lead">Choose an item, then a use. Switch play styles to see how assistance changes while the underlying object rule stays the same.</p>
<div class="lab"><div class="mode-row"><div class="controls" role="group" aria-label="Play style"><button class="toggle" data-mode="simple" aria-pressed="true">Simple Play · starting at 3</button><button class="toggle" data-mode="explore" aria-pressed="false">Explore & Stories · starting at 6</button></div><p>Changeable preferences, not locked age levels.</p></div><div class="toy-row" role="group" aria-label="Choose an object">{{TOYS}}</div><div class="lab-body"><div class="identity"><h3 id="toy-name">Bucket</h3><p id="toy-identity"></p><div id="actions" class="action-row" role="group" aria-label="Object uses"></div><div class="gesture"><strong id="gesture-label"></strong><span id="gesture-text"></span></div></div><div class="outcome" aria-live="polite"><div class="target" id="target"></div><p class="result" id="result"></p><div class="change" id="change"></div><p class="next" id="next"></p></div></div><p class="lab-note">Interactive design explanation, not a playable game or a recording of Toca/Sago gameplay. All examples here are proposed Bluey game behavior. No generated audio is included.</p></div>
<div class="mini-path"><strong>A chain children could discover</strong>Fill the bucket → fill a tray → float a boat → spill a little → wipe it up → squeeze the sponge → water a flower.</div></section>
<section class="section supp-report" id="research"><p class="eyebrow">Source findings and practical implementation</p><h2>The research and revised plan</h2><div class="report-layout"><aside class="contents"><h3>In this guide</h3>{{TOC}}</aside><article class="report">{{BODY}}</article></div></section>
<footer class="footer"><p>Research checked September 23, 2026. Source descriptions, proposed design, and untested implementation are distinguished in the report.</p><a href="toca-piknik-interaction-research-2026-09-23.md">Editable research file</a><a href="bluey-game-research-2026-09-23.html">Original Bluey guide & characters</a></footer></main>
<script>
const toys={{DATA}};let toyIndex=0,actionIndex=0,mode='simple';
function render(){const t=toys[toyIndex],a=t.actions[actionIndex];
 document.getElementById('toy-name').textContent=t.name;
 document.getElementById('toy-identity').textContent=t.identity;
 document.getElementById('gesture-label').textContent=mode==='simple'?'Simple Play assistance':'Explore & Stories controls';
 document.getElementById('gesture-text').textContent=a[mode];
 document.getElementById('target').textContent=a.target;
 document.getElementById('result').textContent=a.result;
 document.getElementById('change').textContent='State change: '+a.change;
 document.getElementById('next').textContent='Then try: '+a.next;
 document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.mode===mode));
 document.querySelectorAll('[data-toy]').forEach(b=>b.setAttribute('aria-pressed',Number(b.dataset.toy)===toyIndex));
 const row=document.getElementById('actions');row.replaceChildren();
 t.actions.forEach((action,i)=>{const b=document.createElement('button');b.className='action';b.textContent=action.name;b.setAttribute('aria-pressed',i===actionIndex);b.addEventListener('click',()=>{actionIndex=i;render();document.querySelectorAll('#actions button')[i].focus()});row.append(b)});
}
document.querySelectorAll('[data-toy]').forEach(b=>b.addEventListener('click',()=>{toyIndex=Number(b.dataset.toy);actionIndex=0;render()}));
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;render()}));
render();
</script></body></html>'''
toy_buttons = "".join(f'<button class="toy" data-toy="{i}" aria-pressed="{str(i == 0).lower()}"><span class="emoji" aria-hidden="true">{t["icon"]}</span><strong>{t["name"]}</strong></button>' for i,t in enumerate(toys))
output = (template.replace("{{STYLE}}",style).replace("{{TOYS}}",toy_buttons).replace("{{TOC}}",md.toc).replace("{{BODY}}",body).replace("{{DATA}}",json.dumps(toys,ensure_ascii=False).replace("</","<\\/")))
(ROOT / f"{BASE}.html").write_text(output,encoding="utf-8")
print(f"Created {BASE}.html; {len(source.split())} report words; {len(toys)} objects; {sum(len(t['actions']) for t in toys)} interaction examples")
